<a href="https://colab.research.google.com/github/EsrinErdem/Movie-Recommandation-System/blob/main/CaeaFlix_Recommandation_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CAEAFLIX - RECOMMANDATION SYSTEM 

In [ ]:
#We import usefull libraries
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
df=pd.read_csv('df_finish_v4')
df.drop(columns=['Unnamed: 0'],inplace=True)

In [ ]:
df.shape

(14842, 24)

In [ ]:
df.columns

Index(['id_tmdb', 'tconst', 'movies_keywords', 'companies', 'movies_websites',
       'movies_popularity', 'nconst', 'primaryTitle', 'genres',
       'movies_poster', 'movies_budget', 'movies_overview', 'movies_revenue',
       'iso_global', 'actors', 'actress', 'producer', 'director', 'writer',
       'startYear', 'runtimeMinutes', 'averageRating', 'numVotes',
       'diffusion'],
      dtype='object')

In [ ]:
#We select the features to use for the recommandation system (only string)
features = ['movies_keywords', 'primaryTitle','genres', 'director','actors','actress','companies','movies_overview']

#We clean them
for feature in features:
    df[feature] = df[feature].str.replace("[","")
    df[feature] = df[feature].str.replace("]","")
    df[feature] = df[feature].fillna('')


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  import sys


In [ ]:
df[['movies_keywords', 'primaryTitle','genres', 'director','actors','actress','companies']]

movies_keywords  \
0      'lover (female)', "love of one's life", 'time ...   
1      '1970s', 'comeback', 'satire', 'film in film',...   
2                                                          
3                                  'fairy tale', 'anime'   
4                          'biography', 'film directing'   
...                                                  ...   
14837                                                      
14838                                                      
14839  'gypsy', 'world war i', 'flashback', 'gore', '...   
14840                                        'espionage'   
14841  'inquisition', 'female friendship', 'witchcraf...   

                                       primaryTitle  \
0                                    Kate & Leopold   
1                        The Other Side of the Wind   
2                                   Libera, My Love   
3                                The Little Mermaid   
4      Kenji Mizoguchi: The Life of a Film Director   
...                                             ...   
14837                                       Herself   
14838                                        Jessie   
14839                                    The Cursed   
14840                                       Le lion   
14841                                         Coven   

                                    genres                          director  \
0         'Comedy',  'Fantasy',  'Romance'                   'James Mangold'   
1                                  'Drama'                    'Orson Welles'   
2                                  'Drama'                 'Mauro Bolognini'   
3      'Adventure',  'Drama',  'Animation'  'Tomoharu Katsumata', 'Tim Reid'   
4              'Biography',  'Documentary'                   'Kaneto Shindô'   
...                                    ...                               ...   
14837                              'Drama'                  'Phyllida Lloyd'   
14838                 'Thriller', 'Horror'                 'Aswani Kumar V.'   
14839     'Fantasy',  'Horror',  'Mystery'                      'Sean Ellis'   
14840                             'Comedy'          'Ludovic Colbeau-Justin'   
14841                   'History', 'Drama'                    'Pablo Agüero'   

                                                  actors  \
0      'Hugh Jackman', 'Liev Schreiber', 'Breckin Meyer'   
1                     'John Huston', 'Peter Bogdanovich'   
2        'Adolfo Celi', 'Philippe Leroy', 'Bruno Cirino'   
3                       'Tarô Shigaki', 'Hideki Shibata'   
4                                              'unknown'   
...                                                  ...   
14837                               'Ian Lloyd Anderson'   
14838               'Atul Kulkarni', 'Kabir Duhan Singh'   
14839                 'Alistair Petrie', 'Boyd Holbrook'   
14840    'Dany Boon', 'Samuel Jouy', 'Philippe Katerine'   
14841                 'Alex Brendemühl', 'Daniel Fanego'   

                                                 actress  \
0                                             'Meg Ryan'   
1                         'Susan Strasberg', 'Oja Kodar'   
2                                    'Claudia Cardinale'   
3                     'Mariko Miyagi', 'Fumie Kashiyama'   
4                                              'unknown'   
...                                                  ...   
14837  'Clare Dunne', 'Molly McCann', "Ruby Rose O'Hara"   
14838                 'Ashima Narwal', 'Sritha Chandana'   
14839                     'Kelly Reilly', 'Roxane Duran'   
14840                                       'Anne Serra'   
14841                'Garazi Urkola', 'Amaia Aberasturi'   

                                               companies  
0                           'Konrad Pictures', 'Miramax'  
1                    'SACI', "Les Films de l'Astrophore"  
2                       'Roberto Loyola Cinematografica'  
3                   

In [ ]:
#We combine each features of each rows together
def combined_features(row):
    return row['movies_keywords']+" "+row['genres']+" "+row['companies']+" "+row['actors']+" "+row['actress']+" "+row['director']+" "+row['primaryTitle']
df["combined_features"] = df.apply(combined_features, axis =1)

In [ ]:
#We use NLP to count each words presence and create binary lists 
cv = CountVectorizer()

#We train and scale our features 
count_matrix = cv.fit_transform(df["combined_features"])
print("Count Matrix:", count_matrix.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
df[df.primaryTitle.str.contains('Boss')]

id_tmdb     tconst                                    movies_keywords  \
6825     5206.0  tt0469754                              'office', 'it-expert'   
9578    51540.0  tt1499658  'bad boss', 'employee', 'death of father', 'st...   
10740  227159.0  tt2170439  'prison', 'kidnapping', 'sex addiction', 'sequ...   
11246  151036.0  tt2577622  'cheating', 'emigration', 'visa', 'train', 'fa...   
11316  323676.0  tt2702724  'business woman', 'ex-con', 'duringcreditsstin...   
12097  295693.0  tt3874544  'baby', 'family relationships', 'sibling rival...   
13623  459151.0  tt6932874  'baby', 'boss', 'sequel', 'sibling', 'family',...   
13935  513310.0  tt7638348                                        'time loop'   

                                               companies  \
6825   'Zentropa Entertainments', 'Memfis Film', 'Slo...   
9578              'New Line Cinema', 'Rat Entertainment'   
10740  'New Line Cinema', 'BenderSpink', 'RatPac Ente...   
11246                                                      
11316  'Universal Pictures', 'On the Day', 'Gary Sanc...   
12097                             'DreamWorks Animation'   
13623       'DreamWorks Animation', 'Universal Pictures'   
13935  'WarParty Films', 'Highland Film Group', 'Inge...   

                                         movies_websites  movies_popularity  \
6825                 http://www.direktorenfordethele.dk/             10.263   
9578   http://horriblebossesmovie.warnerbros.com/inde...             30.626   
10740                                                NaN             31.619   
11246                                                NaN              1.596   
11316                        http://www.thebossfilm.com/             14.436   
12097             http://www.dreamworks.com/thebossbaby/             40.770   
13623  https://www.dreamworks.com/movies/the-boss-baby-2            517.176   
13935  https://www.hulu.com/movie/boss-level-622e81d6...             40.273   

                                                  nconst  \
6825   ['nm0001885', 'nm0934668', 'nm0296144', 'nm030...   
9578   ['nm0000867', 'nm0711840', 'nm0197855', 'nm000...   
10740  ['nm0000867', 'nm0000098', 'nm0197855', 'nm007...   
11246  ['nm0756533', 'nm0663967', 'nm0226770', 'nm195...   
11316  ['nm0376260', 'nm0002071', 'nm0565250', 'nm022...   
12097  ['nm0000285', 'nm0000114', 'nm0569891', 'nm000...   
13623  ['nm0000285', 'nm0000285', 'nm0000285', 'nm056...   
13935  ['nm0000154', 'nm0000154', 'nm0000154', 'nm000...   

                           primaryTitle                                genres  \
6825                 The Boss of It All                              'Comedy'   
9578                    Horrible Bosses                    'Comedy',  'Crime'   
10740                 Horrible Bosses 2                    'Comedy',  'Crime'   
11246                           My Boss                              'Comedy'   
11316                          The Boss                              'Comedy'   
12097                     The Boss Baby  'Adventure',  'Comedy',  'Animation'   
13623  The Boss Baby 2: Family Business  'Adventure',  'Comedy',  'Animation'   
13935                        Boss Level     'Mystery',  'Thriller',  'Sci-Fi'   

                                           movies_poster  ...  \
6825   https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
9578   https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
10740  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
11246  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
11316  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
12097  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
13623  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   
13935  https://www.themoviedb.org/t/p/w600_and_h900_b...  ...   

                                                 actress  \
6825                                           'unknown'   
9578                                           '

In [ ]:
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
  if movie[0] != movie_index:
      print(get_title_from_index(movie[0]))
      i=i+1
      #We fix the number of recommandations we want to display
      print()
      if i>3:
          break

['Endings, Beginnings'
 'An artist dumps her longtime boyfriend, but her attempt to take a break from dating ends when she quickly finds herself in two passionate romances.'
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/5yfJDjTp6n8QXN0M9aGCYpqahXZ.jpg'
 'http://www.samuelgoldwynfilms.com/endings-beginnings/'
 "'Matthew Gray Gubler', 'Sebastian Stan', 'Jamie Dornan'"
 "'Shailene Woodley'" "'Drake Doremus'" "'Drama'" 5.6 2019]

['White Palace'
 "Max Baron is a Jewish advertising executive in his 20s who's still getting over the death of his wife. Nora Baker is a 40-something diner waitress who enjoys the wilder side of life. Mismatched or not, their attraction is instant and smoldering. With time, however, their class and age differences become an obstacle in their relationship, especially since Max can't keep Nora a secret from his Jewish friends and upper-crust associates forever."
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/8H63Gjhfa5f2zkXgEuFA2ThdDJ6.jpg'
 nan "'Jam

Next steps :
* Recommandations based on director only
* Recommandations based on companies only
* Recommandations based on actors/actress only
* Split in two df : movies / anime or three df / vintage ?
* Tenter du NLP sur la colonne overview et primaryTitle

# Recommandations based on director only

In [ ]:
#We combine each features of each rows together
def combined_features(row):
    return row['director']
df["combined_features_director"] = df.apply(combined_features, axis =1)

In [ ]:
#We use NLP to count each words presence and create binary lists 
cv = CountVectorizer()

#We train and scale our features 
count_matrix1 = cv.fit_transform(df["combined_features_director"])
print("Count Matrix:", count_matrix1.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix1)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
    if movie[0] != movie_index:
        print(get_title_from_index(movie[0]))
        i=i+1
        #We fix the number of recommandations we want to display
        print()
        if i>3:
            break

['Aliens'
 "When Ripley's lifepod is found by a salvage crew over 50 years later, she finds that terra-formers are on the very planet they found the alien species. When the company sends a family of colonists out to investigate her story—all contact is lost with the planet and colonists. They enlist Ripley and the colonial marines to return and search for answers."
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/r1x5JGpyqZU8PYhbs4UcrO1Xb6x.jpg'
 'https://www.20thcenturystudios.com/movies/aliens'
 "'Michael Biehn', 'Michael Biehn', 'Michael Biehn', 'Michael Biehn', 'Michael Biehn', 'Michael Biehn', 'Michael Biehn', 'Paul Reiser', 'Paul Reiser', 'Paul Reiser', 'Paul Reiser', 'Paul Reiser', 'Paul Reiser', 'Paul Reiser'"
 "'Sigourney Weaver', 'Sigourney Weaver', 'Sigourney Weaver', 'Sigourney Weaver', 'Sigourney Weaver', 'Sigourney Weaver', 'Sigourney Weaver', 'Carrie Henn', 'Carrie Henn', 'Carrie Henn', 'Carrie Henn', 'Carrie Henn', 'Carrie Henn', 'Carrie Henn'"
 "'James Cameron', '

In [ ]:
df.columns

Index(['id_tmdb', 'tconst', 'movies_keywords', 'companies', 'movies_websites',
       'movies_popularity', 'nconst', 'primaryTitle', 'genres',
       'movies_poster', 'movies_budget', 'movies_overview', 'movies_revenue',
       'iso_global', 'actors', 'actress', 'producer', 'director', 'writer',
       'startYear', 'runtimeMinutes', 'averageRating', 'numVotes', 'diffusion',
       'combined_features', 'combined_features_director'],
      dtype='object')

# Recommandations based on companies only

In [ ]:
#We combine each features of each rows together
def combined_features(row):
    return row['companies']
df["combined_features_companies"] = df.apply(combined_features, axis =1)

In [ ]:
#We use NLP to count each words presence and create binary lists 
cv = CountVectorizer()

#We train and scale our features 
count_matrix2 = cv.fit_transform(df["combined_features_companies"])
print("Count Matrix:", count_matrix2.toarray())

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [ ]:
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix2)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','companies','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
    if movie[0] != movie_index:
        print(get_title_from_index(movie[0]))
        i=i+1
        #We fix the number of recommandations we want to display
        print()
        if i>3:
            break

['True Lies'
 'A fearless, globe-trotting, terrorist-battling secret agent has his life turned upside down when he discovers his wife might be having an affair with a used car salesman while terrorists smuggle nuclear war heads into the United States.'
 "'Lightstorm Entertainment', '20th Century Fox'"
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/pweFTnzzTfGK68woSVkiTgjLzWm.jpg'
 nan "'Arnold Schwarzenegger', 'Bill Paxton', 'Tom Arnold'"
 "'Jamie Lee Curtis'" "'James Cameron'" " 'Thriller', 'Action',  'Comedy'"
 7.3 1994]

['Strange Days'
 'Set in the year 1999 during the last days of the old millennium, the movie tells the story of Lenny Nero, an ex-cop who now deals with data-discs containing recorded memories and emotions. One day he receives a disc which contains the memories of a murderer killing a prostitute. Lenny investigates and is pulled deeper and deeper in a whirl of blackmail, murder and rape. Will he survive and solve the case?'
 "'Lightstorm Entertainment', '20th

# Recommandations based on actors/actress only

In [ ]:
def combined_features(row):
        return row['actors']+" "+row['actress']
df["combined_features_actors_actress"] = df.apply(combined_features, axis =1)
cv = CountVectorizer()
#We train and scale our features 
count_matrix3 = cv.fit_transform(df["combined_features_actors_actress"])
print("Count Matrix:", count_matrix3.toarray())
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix3)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','companies','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
    if movie[0] != movie_index:
        print(get_title_from_index(movie[0]))
        i=i+1
        #We fix the number of recommandations we want to display
        print()
        if i>3:
            break

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['Revolutionary Road'
 'A young couple living in a Connecticut suburb during the mid-1950s struggle to come to terms with their personal problems while trying to raise their two children. Based on a novel by Richard Yates.'
 "'Scott Rudin Productions', 'BBC Films', 'Neal Street Productions', 'Evamere Entertainment', 'DreamWorks Pictures', 'Goldcrest'"
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1jYKJEGcgbkEjlKuY94Dv7BVe1P.jpg'
 nan "'Leonardo DiCaprio', 'Christopher Fitzgerald', 'Jonathan Roumie'"
 "'Kate Winslet'" "'Sam Mendes'" "'Drama',  'Romance'" 7.3 2008]

['The Aviator'
 'A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.'
 '\'Mi

# Split in two df : movies / anime or three df / vintage ?

# Tenter du NLP sur la colonne overview et primaryTitle

In [ ]:
df.columns

Index(['id_tmdb', 'tconst', 'movies_keywords', 'companies', 'movies_websites',
       'movies_popularity', 'nconst', 'primaryTitle', 'genres',
       'movies_poster', 'movies_budget', 'movies_overview', 'movies_revenue',
       'iso_global', 'actors', 'actress', 'producer', 'director', 'writer',
       'startYear', 'runtimeMinutes', 'averageRating', 'numVotes', 'diffusion',
       'combined_features', 'combined_features_director',
       'combined_features_companies', 'combined_features_actors_actress'],
      dtype='object')

In [ ]:
def combined_features(row):
      return row['movies_overview']+" "+row['genres']+" "+row['companies']+" "+row['actors']+" "+row['actress']+" "+row['director']+" "+row['primaryTitle']
df["combined_features_overview"] = df.apply(combined_features, axis =1)
cv = CountVectorizer()
#We train and scale our features 
count_matrix4 = cv.fit_transform(df["combined_features_actors_actress"])
print("Count Matrix:", count_matrix4.toarray())
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix4)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','companies','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
    if movie[0] != movie_index:
        print(get_title_from_index(movie[0]))
        i=i+1
        #We fix the number of recommandations we want to display
        print()
        if i>3:
            break

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['Revolutionary Road'
 'A young couple living in a Connecticut suburb during the mid-1950s struggle to come to terms with their personal problems while trying to raise their two children. Based on a novel by Richard Yates.'
 "'Scott Rudin Productions', 'BBC Films', 'Neal Street Productions', 'Evamere Entertainment', 'DreamWorks Pictures', 'Goldcrest'"
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1jYKJEGcgbkEjlKuY94Dv7BVe1P.jpg'
 nan "'Leonardo DiCaprio', 'Christopher Fitzgerald', 'Jonathan Roumie'"
 "'Kate Winslet'" "'Sam Mendes'" "'Drama',  'Romance'" 7.3 2008]

['The Aviator'
 'A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.'
 '\'Mi

# overview avec nlp nettoiyage

In [ ]:
# !pip install -U pip setuptools wheel
# !pip install -U spacy
# !python -m spacy download en_core_web_sm

In [ ]:
import nltk
nltk.download('popular')
import spacy
nlp = spacy.load('en_core_web_sm')
tokenizer=nltk.RegexpTokenizer(r"\w+")
def clean(sentence="You are better when I am well."):
  sent_tokens = nlp(sentence)  
  lema_str = ' '.join(word.lemma_ for word in sent_tokens)
  lema_str=lema_str.lower()
  txt_puntuation=tokenizer.tokenize(lema_str)
  tokens_clean = []
  for words in txt_puntuation:
    if words not in nltk.corpus.stopwords.words("english"):
      tokens_clean.append(words)
  tokens_str = ' '.join(word for word in tokens_clean)
  return tokens_str
clean()

[nltk_data] Downloading collection 'popular'
[nltk_data]    | 
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nlt

'pron well pron well'

In [ ]:
df['clean_overview']=df['movies_overview'].apply(lambda x: clean(x))
df['clean_overview']

0        pron scientist ex boyfriend discover portal tr...
1        surround fan skeptic grizzle director j j jake...
2        director mauro bolognini insert story fascist ...
3        story beautiful mermaid give kingdom pron belo...
4        kenji mizoguchi life film director aru eiga ka...
                               ...                        
14837    struggle provide pron daughter safe happy home...
14838    set abandon house film follow team professiona...
14839    late 19th century brutal land baron slaughter ...
14840    psychiatric hospital patient pretend crazy cha...
14841    french basque country year 1609 man small fish...
Name: clean_overview, Length: 14842, dtype: object

In [ ]:
features = ['clean_overview']

#We clean them
for feature in features:
    df[feature] = df[feature].str.replace("[","")
    df[feature] = df[feature].str.replace("]","")
    df[feature] = df[feature].fillna('')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  


In [ ]:
def combined_features(row):
      return row['clean_overview']+" "+row['genres']+" "+row['companies']+" "+row['actors']+" "+row['actress']+" "+row['director']+" "+row['primaryTitle']
df["combined_features_overview_cleaned"] = df.apply(combined_features, axis =1)
cv = CountVectorizer()
#We train and scale our features 
count_matrix5 = cv.fit_transform(df["combined_features_actors_actress"])
print("Count Matrix:", count_matrix5.toarray())
#We create the recommandation system function
movie_user_likes = "Titanic"

#We find the index with the title entered by the consumer
def get_index_from_title(primaryTitle):
    return df[df.primaryTitle == primaryTitle].index.values[0]
movie_index = get_index_from_title(movie_user_likes)

#We use the index to create a list of similar movies with cosine_sim function which will compare the binary lists
cosine_sim = cosine_similarity(count_matrix5)
similar_movies = list(enumerate(cosine_sim[movie_index]))

#We sort by the best scores
sorted_similar_movies = sorted(similar_movies, key=lambda x:x[1], reverse=True)

#We display the results
def get_title_from_index(index):
    return df[df.index == index][["primaryTitle",'movies_overview','companies','movies_poster','movies_websites','actors','actress','director','genres','averageRating','startYear']].values[0]
i=0

#We don't want to display the nearest neigbour which is actually the movie the consumer typed
for movie in sorted_similar_movies[0:]:
    if movie[0] != movie_index:
        print(get_title_from_index(movie[0]))
        i=i+1
        #We fix the number of recommandations we want to display
        print()
        if i>3:
            break

Count Matrix: [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
['Revolutionary Road'
 'A young couple living in a Connecticut suburb during the mid-1950s struggle to come to terms with their personal problems while trying to raise their two children. Based on a novel by Richard Yates.'
 "'Scott Rudin Productions', 'BBC Films', 'Neal Street Productions', 'Evamere Entertainment', 'DreamWorks Pictures', 'Goldcrest'"
 'https://www.themoviedb.org/t/p/w600_and_h900_bestv2/1jYKJEGcgbkEjlKuY94Dv7BVe1P.jpg'
 nan "'Leonardo DiCaprio', 'Christopher Fitzgerald', 'Jonathan Roumie'"
 "'Kate Winslet'" "'Sam Mendes'" "'Drama',  'Romance'" 7.3 2008]

['The Aviator'
 'A biopic depicting the life of filmmaker and aviation pioneer Howard Hughes from 1927 to 1947, during which time he became a successful film producer and an aviation magnate, while simultaneously growing more unstable due to severe obsessive-compulsive disorder.'
 '\'Mi

In [ ]:
# Les mêmes résultats ont été obtenus même 
# si le nettoyage a été fait. Je pense qu'il vaudra mieux utiliser 
# key words à la place en termes de recommandation.